import time
import math
	

def mathcalculatorEN():
	print("Powered by sekal")
	print("**************************************************")
	print("Select action")
	print("**************************************************")
	print("1 - Addition")
	print("2 - Subtraction")
	print("3 - Multiplication")
	print("4 - Division")
	print("5 - Logarithms")
	print("6 - Radian in degress")
	print("7 - Degrees in radians")
	print("8 - Take the root of a number")
	print("0 - Select language")
	answer = input()
	if answer == "1":
		print("Write the first number")
		firstplus = input()
		print("Write the second number")
		secondplus = input()
		time.sleep(0.5)
		resultplus = int(firstplus)+int(secondplus)
		print("**************************************************")
		print(f"Result = {resultplus}")
		mathcalculatorEN()
	if answer == "2":
		print("Write the first number")
		firstminus = input()
		print("Write the second number")
		secondminus = input()
		time.sleep(0.5)
		resultminus = int(firstminus)-int(secondminus)
		print("**************************************************")
		print(f"Result = {resultminus}")
		mathcalculatorEN()
	if answer == "3":
		print("Write the first number")
		firstmultiplier = input()
		print("Write the second number")
		secondmultiplier = input()
		time.sleep(0.5)
		resultmultiplier = int(firstmultiplier)*int(secondmultiplier)
		print("**************************************************")
		print(f"Result = {resultmultiplier}")
		mathcalculatorEN()
	if answer == "4":
		print("Write the first number")
		firstdivider = input()
		print("Write the second number")
		seconddivider = input()
		time.sleep(0.5)
		resultdivider = int(firstdivider)/int(seconddivider)
		print("**************************************************")
		print(f"Result = {resultdivider}")
		mathcalculatorEN()
	if answer == "5":
		print("Write the base of logarithm")
		firstlog = input()
		print("Write a logarithm argument")
		secondlog = input()
		time.sleep(0.5)
		resultlog = math.log(int(secondlog), int(firstlog))
		print("**************************************************")
		print(f"Result = {resultlog}")
		mathcalculatorEN()
	if answer == "6":
		print("Write the number of radians")
		rad = input()
		time.sleep(0.5)
		resultrad = math.degrees(int(rad))
		print("**************************************************")
		print(f"Result = {resultrad}")
		mathcalculatorEN()
	if answer == "7":
		print("Write the number of degrees")
		grad = input()
		time.sleep(0.5)
		resultgrad = math.radians(int(grad))
		print("**************************************************")
		print(f"Result = {resultgrad}")
		mathcalculatorEN()
	if answer == "8":
		print("Write the number from which you want to take the root")
		koren = input()
		time.sleep(0.5)
		resultkoren = math.sqrt(int(koren))
		print("**************************************************")
		print(f"Result = {resultkoren}")
		mathcalculatorEN()
	if answer == "0":
		selectlanguage()
def mathcalculator():
	print("Powered by sekal")
	print("**************************************************")
	print("Выберите действие которое хотите сделать с числами")
	print("**************************************************")
	print("1 - Сложение")
	print("2 - Вычитание")
	print("3 - Умножение")
	print("4 - Деление")
	print("5 - Логарифмы")
	print("6 - Радианы в градусы")
	print("7 - Градусы в радианы")
	print("8 - Извлечь корень")
	print("0 - Изменить язык")
	answer = input()
	if answer == "1":
		print("Впишите первое число")
		firstplus = input()
		print("Впишите второе число")
		secondplus = input()
		time.sleep(0.5)
		resultplus = int(firstplus)+int(secondplus)
		print("**************************************************")
		print(f"Результат = {resultplus}")
		mathcalculator()
	if answer == "2":
		print("Впишите первое число")
		firstminus = input()
		print("Впишите второе число")
		secondminus = input()
		time.sleep(0.5)
		resultminus = int(firstminus)-int(secondminus)
		print("**************************************************")
		print(f"Результат = {resultminus}")
		mathcalculator()
	if answer == "3":
		print("Впишите первое число")
		firstmultiplier = input()
		print("Впишите второе число")
		secondmultiplier = input()
		time.sleep(0.5)
		resultmultiplier = int(firstmultiplier)*int(secondmultiplier)
		print("**************************************************")
		print(f"Результат = {resultmultiplier}")
		mathcalculator()
	if answer == "4":
		print("Впишите первое число")
		firstdivider = input()
		print("Впишите второе число")
		seconddivider = input()
		time.sleep(0.5)
		resultdivider = int(firstdivider)/int(seconddivider)
		print("**************************************************")
		print(f"Результат = {resultdivider}")
		mathcalculator()
	if answer == "5":
		print("Впишите основание")
		firstlog = input()
		print("Впишите аргумент")
		secondlog = input()
		time.sleep(0.5)
		resultlog = math.log(int(secondlog), int(firstlog))
		print("**************************************************")
		print(f"Результат = {resultlog}")
		mathcalculator()
	if answer == "6":
		print("Впишите кол-во радиан")
		rad = input()
		time.sleep(0.5)
		resultrad = math.degrees(int(rad))
		print("**************************************************")
		print(f"Результат = {resultrad}")
		mathcalculator()
	if answer == "7":
		print("Впишите кол-во градусов")
		grad = input()
		time.sleep(0.5)
		resultgrad = math.radians(int(grad))
		print("**************************************************")
		print(f"Результат = {resultgrad}")
		mathcalculator()
	if answer == "8":
		print("Напишите число из которого нужно извлечь корень")
		koren = input()
		time.sleep(0.5)
		resultkoren = math.sqrt(int(koren))
		print("**************************************************")
		print(f"Результат = {resultkoren}")
		mathcalculator()
	if answer == "0":
		selectlanguage()

def selectlanguage():
	print("Select language")
	print("1 - English")
	print("2 - Russian")
	Language = input()
	if Language == "1":
		mathcalculatorEN()
	if Language == "2":
		mathcalculator() 
		

selectlanguage()
