import time
import math
def mathcalculator():
	print("Powered by sekal")
	print("**************************************************")
	print("Выберите действие которое хотите сделать с числами")
	print("**************************************************")
	print("1 - Сложение")
	print("2 - Вычитание")
	print("3 - Умножение")
	print("4 - Деление")
	print("5 - Логарифмы")
	answer = input(int)
	if answer == "1":
		print("Впишите первое число")
		firstplus = input()
		print("Впишите второе число")
		secondplus = input()
		time.sleep(0.5)
		resultplus = int(firstplus)+int(secondplus)
		print("**************************************************")
		print(f"Результат = {resultplus}")
		mathcalculator()
	if answer == "2":
		print("Впишите первое число")
		firstminus = input()
		print("Впишите второе число")
		secondminus = input()
		time.sleep(0.5)
		resultminus = int(firstminus)-int(secondminus)
		print("**************************************************")
		print(f"Результат = {resultminus}")
		mathcalculator()
	if answer == "3":
		print("Впишите первое число")
		firstmultiplier = input()
		print("Впишите второе число")
		secondmultiplier = input()
		time.sleep(0.5)
		resultmultiplier = int(firstmultiplier)*int(secondmultiplier)
		print("**************************************************")
		print(f"Результат = {resultmultiplier}")
		mathcalculator()
	if answer == "4":
		print("Впишите первое число")
		firstdivider = input()
		print("Впишите второе число")
		seconddivider = input()
		time.sleep(0.5)
		resultdivider = int(firstdivider)/int(seconddivider)
		print("**************************************************")
		print(f"Результат = {resultdivider}")
		mathcalculator()
	if answer == "5":
		print("Впишите основание")
		firstlog = input()
		print("Впишите аргумент")
		secondlog = input()
		time.sleep(0.5)
		resultlog = math.log(int(secondlog), int(firstlog))
		print("**************************************************")
		print(f"Результат = {resultlog}")
		mathcalculator()
mathcalculator()
